CREATE TABLE page_suggestions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id         BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  author_id       BIGINT NOT NULL REFERENCES users(id),
  title           TEXT,
  body            TEXT NOT NULL,
  props           JSONB,
  base_revision_id BIGINT REFERENCES page_revisions(id),
  status          TEXT NOT NULL DEFAULT 'open'
                  CHECK (status IN ('open','approved','rejected','withdrawn')),
  summary         TEXT,
  review_note     TEXT,
  applied_hunks   JSONB,
  reviewed_by     BIGINT REFERENCES users(id),
  reviewed_at     TEXT,
  created_at      TEXT NOT NULL DEFAULT tela_now(),
  updated_at      TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX page_suggestions_page_status_idx
  ON page_suggestions (page_id, status, id DESC);
